In [1]:
import pandas as pd
import numpy as np

# 1 Numpy Array Creation Methods

### Create a NumPy array from a python list

In [2]:
a = [1,2,3]
np.array(a)

array([1, 2, 3])

In [3]:
type(np.array(a))

numpy.ndarray

In [4]:
a = [[1,2,3], [4,5,6]]
np.array(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a = [[1,2,3], [4,5,6]]
np.array(a, dtype=np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### Create a NumPy array of Zeros

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### Create a NumPy array of Ones

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### Create an Identity Numpy Array

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Create an equally spaced Numpy Array with a specific step

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [13]:
np.arange(5,11,2)

array([5, 7, 9])

### Create an equally spaced Numpy Array with a specific array size

In [14]:
np.linspace(start=10, stop=20, num=5)

array([10. , 12.5, 15. , 17.5, 20. ])

### Generate a random numpy array

In [17]:
np.random.randint(low=5, high=16, size=5)

array([13, 10,  9, 15,  7])

In [18]:
np.random.random(size=10)

array([0.15642036, 0.96675911, 0.84320696, 0.24563199, 0.09163223,
       0.99128961, 0.41832982, 0.598957  , 0.20514457, 0.69090483])

### Generate NumPy Array from a Pandas Series

In [19]:
s= pd.Series([1,2,3,4], name="col")
np.array(s)

array([1, 2, 3, 4], dtype=int64)

In [20]:
s= pd.Series([1,2,3,4], name="col")
np.asarray(s)

array([1, 2, 3, 4], dtype=int64)

# 2 NumPy Array Manipulation Methods

### Shape of the NumPy Array

In [22]:
a = np.ones((2,3))
print("Shape of the array - Method 1:", np.shape(a))
print("Shape of the array - Method 2:", a.shape)

Shape of the array - Method 1: (2, 3)
Shape of the array - Method 2: (2, 3)


### Reshape the NumPy Array

In [29]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Transpose the NumPy Array

In [30]:
a = np.arange(12).reshape((6,2))
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [31]:
a.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

### Concatenate multiple NumPy arrays to form one NumPy Array

In [32]:
## Concatenate Row-wise

a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
## Concatenate Column-wise

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [34]:
## Concatenate to generate a flat NumPy Array

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

- axis=0 is same as `np.vstack()`.

- axis=1 is same as `np.hstack()`.

### Flatten NumPy Array

In [35]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

### Unique Elements of a NumPy Array

In [36]:
a = np.array([[1,2],[2,3]])
np.unique(a)

array([1, 2, 3])

In [37]:
## Return Unique Rows

a = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])
np.unique(a, axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [38]:
## Return Unique Columns

a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
np.unique(a, axis=1)

array([[1, 3],
       [1, 3],
       [1, 4]])

### Squeeze a NumPy Array

If you want to remove axes of length one from your numpy array, use the np.squeeze() method. 

In [39]:
x = np.array([[[0], [1], [2]]])

In [40]:
x.shape

(1, 3, 1)

In [41]:
np.squeeze(x)

array([0, 1, 2])

In [42]:
np.squeeze(x).shape

(3,)

### Transform NumPy Array to Python List

In [43]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
a.tolist()

[[1, 1, 3], [1, 1, 3], [1, 1, 4]]

# 3 Mathematical Operations on NumPy Arrays

### Trigonometric Functions

In [44]:
a = np.array([1,2,3])
print("Trigonometric Sine   :", np.sin(a))
print("Trigonometric Cosine :", np.cos(a))
print("Trigonometric Tangent:", np.tan(a))

Trigonometric Sine   : [0.84147098 0.90929743 0.14112001]
Trigonometric Cosine : [ 0.54030231 -0.41614684 -0.9899925 ]
Trigonometric Tangent: [ 1.55740772 -2.18503986 -0.14254654]


### Rounding Functions

- Return the element-wise floor using the np.floor() method.

- Return the element-wise ceiling using the np.ceil() method.

- Round to nearest integer using the np.rint() method.

In [45]:
a = np.linspace(1, 2, 5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [46]:
np.floor(a)

array([1., 1., 1., 1., 2.])

In [47]:
np.ceil(a)

array([1., 2., 2., 2., 2.])

In [48]:
np.rint(a)

array([1., 1., 2., 2., 2.])

In [49]:
# Round to given number of decimals using the np.round_() method:

a = np.linspace(1,2,7)
np.round_(a, 2)  # 2 decimal places

array([1.  , 1.17, 1.33, 1.5 , 1.67, 1.83, 2.  ])

### Exponents and logarithms

- Calculate the element-wise exponential using the np.exp() method.

- Calculate the element-wise natural logarithm using the np.log() method.

In [54]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [55]:
np.exp(a).round(2)

array([  2.72,   7.39,  20.09,  54.6 , 148.41])

In [56]:
np.log(a).round(2)

array([0.  , 0.69, 1.1 , 1.39, 1.61])

### Sum and Product

In [57]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [58]:
np.sum(a, axis=0)

array([4, 6])

In [59]:
np.sum(a, axis=1)

array([3, 7])

In [65]:
pd.DataFrame(a)

0  1
0  1  2
1  3  4

In [66]:
a = np.array([[1, 2], [3, 4]])
np.prod(a)

24

In [67]:
np.prod(a, axis=0)

array([3, 8])

In [68]:
np.prod(a, axis=1)

array([ 2, 12])

### Square Root

In [69]:
a = np.array([[1,2], [3,4]])
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

# 4 Matrix and Vector Operations

### Dot Product

In [70]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])
np.dot(a,b)

array([[3, 3],
       [7, 7]])

### Matrix Product

In [71]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

In [72]:
np.matmul(a,b)

array([[3, 3],
       [7, 7]])

In [73]:
a@b

array([[3, 3],
       [7, 7]])

### Vector Norm

In [74]:
a = np.arange(-4, 5)
a

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [75]:
np.linalg.norm(a)

7.745966692414834

In [76]:
np.linalg.norm(a,1)

20.0

# 5 Sorting Methods

### Sort a NumPy Array

In [77]:
a = np.array([[1,4],[3,1]])
a

array([[1, 4],
       [3, 1]])

In [78]:
np.sort(a) # sort based on rows

array([[1, 4],
       [1, 3]])

In [79]:
np.sort(a, axis=None) # sort the flattened array

array([1, 1, 3, 4])

In [81]:
np.sort(a, axis=0) # sort based on columns

array([[1, 1],
       [3, 4]])

### Order of Indices in a Sorted NumPy Array

In [82]:
x = np.array([3,1,2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

# 6 Searching Methods

###  Indices corresponding to Maximum Values

In [83]:
a = np.random.randint(1, 20, 10).reshape(2,5)
a

array([[15, 15,  6, 19,  4],
       [11,  5, 19, 17, 14]])

In [84]:
np.argmax(a) # index in a flattened array

3

In [87]:
a.flatten()

array([15, 15,  6, 19,  4, 11,  5, 19, 17, 14])

In [88]:
np.argmax(a, axis=0) ## indices along columns

array([0, 0, 1, 0, 1], dtype=int64)

In [89]:
np.argmax(a, axis=1) ## indices along rows

array([3, 2], dtype=int64)

To find the index in a non-flattened array, you can do the following:

In [91]:
ind = np.unravel_index(np.argmax(a), a.shape)
ind

(0, 3)

### Indices corresponding to Minimum Values

In [92]:
a = np.random.randint(1, 20, 10).reshape(2,5)
a

array([[15, 11,  4,  4,  7],
       [18, 13, 17, 18, 18]])

In [94]:
np.argmin(a) ## index in a flattend array

2

In [95]:
a.flatten()

array([15, 11,  4,  4,  7, 18, 13, 17, 18, 18])

In [96]:
np.argmin(a, axis=0) ## indices along columns

array([0, 0, 0, 0, 0], dtype=int64)

In [98]:
np.argmin(a, axis=1) ## indices along rows

array([2, 1], dtype=int64)

### Search based on condition

In [99]:
a = np.random.randint(-10, 10, 10)
a

array([ 1, -2,  5,  9,  2, -3, -9, -4, -2, -4])

In [100]:
np.where(a <0, 0, a)

array([1, 0, 5, 9, 2, 0, 0, 0, 0, 0])

### Indices of Non-Zero Elements

In [101]:
a = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
np.nonzero(a)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

# 7 Statistical Methods

### Mean

In [102]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [103]:
np.mean(a, axis=1) # along the row axis

array([1.5, 3.5])

In [104]:
np.mean(a, axis=0) # along the column axis

array([2., 3.])

### Median

In [105]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [106]:
np.median(a, axis=1) # along the row axis

array([1.5, 3.5])

In [107]:
np.median(a, axis=0) # along the column axis

array([2., 3.])

### Standard Deviation

In [108]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [109]:
np.std(a, axis = 1) ## along the row axis

array([0.5, 0.5])

In [110]:
np.std(a, axis = 0) ## along the column axis

array([1., 1.])